import json
nb = json.load(open('npu_gnn_benchmarking.ipynb', encoding='utf-8'))
code = [
    'import glob\n',
    'import pandas as pd\n',
    'import numpy as np\n',
    'import matplotlib.pyplot as plt\n',
    'from pathlib import Path\n',
    'from analysis.plot_config import shorten_label, DOUBLE_COL, IEEE_COLORS, savefig_ieee\n',
    '\n',
    'hw_summaries = glob.glob("results/hw_comparison/*/hw_comparison_summary.csv")\n',
    'hw_list = []\n',
    'for f in hw_summaries:\n',
    '    if "GAT" in f: continue\n',
    '    m_name = Path(f).parent.name\n',
    '    tdf = pd.read_csv(f)\n',
    "    cpu = tdf[tdf['device'] == 'CPU']['avg_latency_ms'].mean()\n",
    "    gpu = tdf[tdf['device'] == 'GPU']['avg_latency_ms'].mean()\n",
    "    npu = tdf[tdf['device'] == 'NPU']['avg_latency_ms'].mean()\n",
    "    hw_list.append({'model': m_name, 'CPU': cpu, 'GPU': gpu, 'NPU': npu})\n",
    '\n',
    'df_hw = pd.DataFrame(hw_list).dropna(subset=["CPU", "NPU"])\n',
    "df_hw['label'] = df_hw['model'].apply(shorten_label)\n",
    "df_hw['GPU_Speedup'] = df_hw['CPU'] / df_hw['GPU']\n",
    "df_hw['NPU_Speedup'] = df_hw['CPU'] / df_hw['NPU']\n",
    '\n',
    'fig, ax = plt.subplots(figsize=DOUBLE_COL)\n',
    'x = np.arange(len(df_hw))\n',
    'w = 0.35\n',
    "ax.bar(x - w/2, df_hw['GPU_Speedup'], w, label='GPU (OpenVINO)', color=IEEE_COLORS[3], edgecolor='k')\n",
    "ax.bar(x + w/2, df_hw['NPU_Speedup'], w, label='NPU (OpenVINO)', color=IEEE_COLORS[0], edgecolor='k')\n",
    '\n',
    "ax.axhline(1, color='red', lw=0.8, ls='--')\n",
    "ax.set_xticks(x); ax.set_xticklabels(df_hw['label'], rotation=45)\n",
    'ax.set_ylabel("Speedup vs. CPU (x)")\n',
    'ax.set_title("NPU vs. GPU Speedup (Relative to CPU Baseline)")\n',
    'ax.legend()\n',
    'savefig_ieee(fig, "results/hw_hardware_comparison")\n',
    'plt.show()\n'
]
nb['cells'][19]['source'] = code
json.dump(nb, open('npu_gnn_benchmarking.ipynb', 'w', encoding='utf-8'), indent=1, ensure_ascii=False)
